name: Compile TEX

# Controls when the action will run. 
on:
  workflow_dispatch:
    branches: [ $default-branch ]
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

# Define jobs
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: report/challenge_summary.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v1
        with:
            name: challenge_summary.pdf
            path: report/challenge_summary.pdf
      - name: Copy PDF
        uses: canastro/copy-file-action@master
        with:
          source: report/challenge_summary.pdf
          target: challenge_summary.pdf
